---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# tacApp

<!-- badges: start -->
<!-- badges: end -->

The goal of tacApp is to help you analyze changes in the power sector between
two time periods. The public source code lives in an [R
package]([here](https://github.com/2DegreesInvesting/tacApp)), and the public
application is available [online](https://twodii.shinyapps.io/tacApp/).

## Usage

* Go to <https://twodii.shinyapps.io/tacApp/>.
* Select a parent company and a technology.
* Click "Apply".

## Output

* A summary of the _real_ and _virtual_ change.
* A breakdown of changes as a plot.
* A breakdown of changes as a downloadable table.

A _real_ change is an increase or decrease in the production capacity. A
_virtual_ change is a change not in the production capacity but in the ownership
of the asset.

## Data

The data is private. You may get it from [Asset
Resolution](https://asset-resolution.com/). If you have access permission you
may get it at <https://github.com/2DegreesInvesting/tacAppPrivateData>.

To update the data start at tacAppPrivateData/data-raw/, then continue at
tacApp/data-raw/.
